### ISSUE TITLE
Publish this template to azure samples browser

### ISSUE THREAD

**Issue by hemarina** [Azure-Samples/azure-postgres-pgvector-python#12]
Since this is a "msft" authorized template in Azure-Samples, we may want to publish it to Microsoft learning page: [Onboarding Samples to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main)

**Comment by pamelafox** [comment]
It is the first result:
https://learn.microsoft.com/en-us/samples/browse/?terms=postgresql

Is there something that makes you think its not there? Some config?
