### ISSUE TITLE
Parameters still need to be passed?

### ISSUE THREAD

**Issue by ImreC** [Azure-Samples/azure-postgres-pgvector-python#27]
Hey! I am using this template for an example deployment of pg vector on Azure. This example seems to be failing with the parameters not all being present in main.bicep. Is it correct that the ones used in pg.bicep need to be defined in main.bicep first and then passed to the module? Or am I missing something obvious? Thanks in advance!

**Comment by pamelafox** [comment]
Hm, I just tested yesterday, and it is deploying fine. Are you using `azd up` per the README, or are you using this via `az deployment sub create`?

**Comment by ImreC** [comment]
I was using az deployment create because the infra needed to be deployed in an existing resource group. I was asking more on a conceptual level, but probably should read some more docs. Thanks for responding!

**Comment by pamelafox** [comment]
Ah okay! The azd CLI has some env variables that it populates itself, like AZURE_ENV_NAME, AZURE_LOCATION, and AZURE_SUBSCRIPTION_ID. You would need to supply them yourself if using `az deployment sub create`. I could also make it possible to specify an existing resource group as a parameter in infra/main.parameters.json in the future.
